#!/bin/sh
set -e

case "$1" in
    configure)

        if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database /usr/share/applications
        fi
        
        if command -v gtk-update-icon-cache >/dev/null 2>&1; then
            gtk-update-icon-cache -f -t /usr/share/icons/hicolor 2>/dev/null || true
        fi
        
        if command -v update-applications >/dev/null 2>&1; then
            update-applications 2>/dev/null || true
        fi
        ;;
esac
